services:
  keto:
    image: oryd/keto:v25.4.0
    ports:
      - "4466:4466" # Read API
      - "4467:4467" # Write API
    expose:
      - 4466
      - 4467
    # networks:
    #   - keto-network
    # volumes:
    # - ./startup.sh:/etc/keto/startup.sh
    # - ./keto.yaml:/etc/keto/keto.yaml
    # - ../permissions/${PERMISSION_TYPE:-group-direct-permission}/namespaces.keto.ts:/etc/keto/namespaces.keto.ts
    # - ../permissions/${PERMISSION_TYPE:-group-direct-permission}/relationships.json:/etc/keto/relationships.json
    entrypoint: ["/bin/sh", "-c"]
    command: ["/etc/keto/startup.sh"]
    develop:
      watch:
        - action: sync
          path: ./startup.sh
          target: /etc/keto/startup.sh
          initial_sync: true
        - action: sync+restart
          path: ./keto.yaml
          target: /etc/keto/keto.yaml
          initial_sync: true
        - action: sync+restart
          path: ../permissions/${PERMISSION_TYPE:-current}/namespaces.keto.ts
          target: /etc/keto/namespaces.keto.ts
          initial_sync: true
        - action: sync+restart
          path: ../permissions/${PERMISSION_TYPE:-current}/relationships.json
          target: /etc/keto/relationships.json
          initial_sync: true

    restart: unless-stopped
    healthcheck:
      test:
        ["CMD", "wget", "-q", "--spider", "http://localhost:4466/health/ready"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 3s

# networks:
#   keto-network:
#     name: keto-network
