version: v0.8.0-alpha.2

dsn: memory

namespaces:
  location: file:///etc/keto/namespaces.keto.ts

log:
  level: info
  format: json

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467
limit:
  max_read_depth: 100
