services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    volumes:
      - ../:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    # networks:
    #   - keto-network
    environment:
      - KETO_READ_URL=http://keto:4466
      - KETO_WRITE_URL=http://keto:4467
      # - PERMISSION_TYPE=group-direct-permission

# networks:
#   keto-network:
#     external: true